# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# see https://www.glfw.org/docs/latest/compile.html
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      # - name: Install deps
      #   run: sudo apt install -y libx11-dev libxrandr-dev libglx-dev libgl-dev libxcursor-dev libgl1-mesa-dev xorg-dev libxi-dev libxext-dev libglfw3-dev
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
