# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# see https://www.glfw.org/docs/latest/compile.html
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: WASM
        shell: pwsh
        run: |
          $Env:GOOS = 'js'
          $Env:GOARCH = 'wasm'
          go build -o fishgame.wasm fishgame
          Remove-Item Env:GOOS
          Remove-Item Env:GOARCH
          $goroot = go env GOROOT
          cp $goroot\lib\wasm\wasm_exec.js .

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            fishgame.wasm
            wasm_exec.js
